### ISSUE TITLE
error when installing tmp:motioneye

### ISSUE THREAD

**Issue by popeyesfx** [fguiet/motioneye-docker#1]
When installing i get the following error message:
Processing /tmp/motioneye
1609.9   Installing build dependencies: started
1673.7   Installing build dependencies: still running...
1687.7   Installing build dependencies: finished with status 'done'
1692.3     Complete output from command python setup.py egg_info:
1692.3     Traceback (most recent call last):
1692.3       File "<string>", line 1, in <module>
1692.3     IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-vtD7Dg/setup.py'
1692.3     
1692.3     ----------------------------------------
1692.9 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-vtD7Dg/

Have followed your instructions to the letter, any advice

**Comment by fguiet** [comment]
Hi @popeyesfx ,
I created this repository 4 years ago...so no doubt there may be some issues to make it work.
So I cannot help you sorry
fred
